#!/usr/bin/perl -w

##HACKABOT_HELP##
# Get a limerick!
# !limerick [number]
##HACKABOT_HELP##

use strict;

my $url = "http://bash.org/?random2";
my $quotesPerPage = 50;

my $msg = <>;
if (defined $msg and $msg =~ /\s+\d+/) {
    print "send $_\n";
    $msg = s/\s+//;
    $url = "http://bash.org/?$1";
    $quotesPerPage = 1;
}

open(PAGE, "lynx -dump '$url' |");

my $chosenQuote = int(rand($quotesPerPage));
my $print = 0;
while (<PAGE>) {
    s/^\s+//;
    s/\s+$//;

    # Since there is a blank line after the quote numbers, consume one blank
    # line after finding a number.
    if (not $print and /^\[\d+\]#\d+/ and not $chosenQuote--) {
        $print = 1;
    }
    elsif ($print == 1 and /^$/) {
        $print = 2;
    }
    elsif ($print == 2 and (/^\[\d+\]#\d+/ or /^$/)) {
        last;
    }
    elsif ($print == 2) {
        print "send $_\n";
    }
}

close(PAGE);
