#!/usr/bin/env python

##HACKABOT_HELP##
# Roll some dice (default 1d6)
# !dice [[NUMd]SIDES[+ADD]]
##HACKABOT_HELP##

import re
import random

import hackabot
from hackabot.client import Client

def roll(num,sides,add):
    total = add
    for i in range(num):
        total += random.randint(1,sides)
    return total

def main():
    hbc = Client()

    msg = hbc.readline()
    nick = hbc.sent_by()
    chan = hbc.channel()

    num = 0
    sides = 0
    add = 0

    if msg:
        m = re.match(r'((\d*)d)?(\d*)(\+(\d*))?', msg)
        _, num, sides, _, add = m.groups()

    if not num:
        num = 1
    else:
        num = int(num)

    if not sides:
        sides = 6
    else:
        sides = int(sides)

    if not add:
        add = 0
    else:
        add = int(add)
        
    result = roll(num,sides,add)

    print "msg %s: You got %s" % (nick, result)

if __name__ == "__main__":
    main()
